// ============================================================
//   MEMOIZE — DEMO SEED API ROUTE
//   Called by Vercel cron job every night at midnight
//   Also callable manually: POST /api/seed
//   Protected by SEED_SECRET env variable
// ============================================================

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const DEMO_USER_ID = "9e51c14a-4510-48d1-9669-ae36db006b4e";

// ── Helpers ───────────────────────────────────────────────────

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function nextReview(daysFromNow: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().split("T")[0];
}

// ── Problems ──────────────────────────────────────────────────

function getProblems() {
  return [
    // ── LEETCODE EASY (10) ──────────────────────────────────

    {
      user_id: DEMO_USER_ID,
      problem_name: "Two Sum",
      platform: "leetcode",
      problem_key: "leetcode-two-sum",
      problem_url: "https://leetcode.com/problems/two-sum/",
      difficulty: "easy",
      tags: ["Array", "Hash Table"],
      pattern: "two_pointers",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach:
        "HashMap to store complement lookup. For each element check if target - nums[i] exists in map.",
      mistakes: "Initially forgot to handle duplicate indices.",
      similar_problems: "Three Sum, Four Sum",
      language: "JavaScript",
      runtime: "4 ms",
      memory: "42.3 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.8,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(18),
      solved_at: daysAgo(82),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Valid Parentheses",
      platform: "leetcode",
      problem_key: "leetcode-valid-parentheses",
      problem_url: "https://leetcode.com/problems/valid-parentheses/",
      difficulty: "easy",
      tags: ["String", "Stack"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach:
        "Stack-based. Push open brackets, pop and verify on close brackets.",
      mistakes: null,
      similar_problems: "Minimum Remove to Make Valid Parentheses",
      language: "JavaScript",
      runtime: "2 ms",
      memory: "38.1 MB",
      sm2_interval: 30,
      sm2_ease_factor: 2.9,
      sm2_repetitions: 5,
      sm2_next_review: nextReview(22),
      solved_at: daysAgo(75),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Best Time to Buy and Sell Stock",
      platform: "leetcode",
      problem_key: "leetcode-best-time-to-buy-and-sell-stock",
      problem_url:
        "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
      difficulty: "easy",
      tags: ["Array", "Dynamic Programming"],
      pattern: "sliding_window",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Track minPrice and maxProfit as we iterate. O(n) single pass.",
      mistakes: null,
      similar_problems: "Best Time to Buy and Sell Stock II",
      language: "JavaScript",
      runtime: "68 ms",
      memory: "50.2 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(8),
      solved_at: daysAgo(55),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Reverse Linked List",
      platform: "leetcode",
      problem_key: "leetcode-reverse-linked-list",
      problem_url: "https://leetcode.com/problems/reverse-linked-list/",
      difficulty: "easy",
      tags: ["Linked List", "Recursion"],
      pattern: "other",
      status: "solved",
      confidence: "medium",
      solve_help: "hints",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach:
        "Iterative with prev, curr, next pointers. Also did recursive version.",
      mistakes: "Kept losing track of next pointer before reassignment.",
      similar_problems: "Reverse Linked List II",
      language: "JavaScript",
      runtime: "72 ms",
      memory: "44.1 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-5),
      solved_at: daysAgo(40),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Climbing Stairs",
      platform: "leetcode",
      problem_key: "leetcode-climbing-stairs",
      problem_url: "https://leetcode.com/problems/climbing-stairs/",
      difficulty: "easy",
      tags: ["Math", "Dynamic Programming"],
      pattern: "dp",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach:
        "Fibonacci pattern. dp[i] = dp[i-1] + dp[i-2]. Space optimized.",
      mistakes: null,
      similar_problems: "House Robber, Jump Game",
      language: "JavaScript",
      runtime: "48 ms",
      memory: "38.5 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.7,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(14),
      solved_at: daysAgo(68),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Contains Duplicate",
      platform: "leetcode",
      problem_key: "leetcode-contains-duplicate",
      problem_url: "https://leetcode.com/problems/contains-duplicate/",
      difficulty: "easy",
      tags: ["Array", "Hash Table"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "HashSet approach. If element already in set return true.",
      mistakes: null,
      similar_problems: "Contains Duplicate II",
      language: "JavaScript",
      runtime: "88 ms",
      memory: "52.1 MB",
      sm2_interval: 30,
      sm2_ease_factor: 2.9,
      sm2_repetitions: 5,
      sm2_next_review: nextReview(26),
      solved_at: daysAgo(88),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Merge Two Sorted Lists",
      platform: "leetcode",
      problem_key: "leetcode-merge-two-sorted-lists",
      problem_url: "https://leetcode.com/problems/merge-two-sorted-lists/",
      difficulty: "easy",
      tags: ["Linked List", "Recursion"],
      pattern: "merge_intervals",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Dummy head node, compare l1 and l2 values iteratively.",
      mistakes: "Forgot edge case when one list is empty.",
      similar_problems: "Merge K Sorted Lists",
      language: "JavaScript",
      runtime: "60 ms",
      memory: "41.8 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-3),
      solved_at: daysAgo(35),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Binary Search",
      platform: "leetcode",
      problem_key: "leetcode-binary-search",
      problem_url: "https://leetcode.com/problems/binary-search/",
      difficulty: "easy",
      tags: ["Array", "Binary Search"],
      pattern: "binary_search",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach:
        "Classic binary search. mid = left + (right - left) / 2 to avoid overflow.",
      mistakes: null,
      similar_problems: "Search a 2D Matrix",
      language: "JavaScript",
      runtime: "52 ms",
      memory: "42.0 MB",
      sm2_interval: 30,
      sm2_ease_factor: 2.9,
      sm2_repetitions: 5,
      sm2_next_review: nextReview(20),
      solved_at: daysAgo(70),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Maximum Depth of Binary Tree",
      platform: "leetcode",
      problem_key: "leetcode-maximum-depth-of-binary-tree",
      problem_url:
        "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
      difficulty: "easy",
      tags: ["Tree", "DFS"],
      pattern: "dfs",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Recursive DFS. return 1 + max(depth(left), depth(right)).",
      mistakes: null,
      similar_problems: "Minimum Depth of Binary Tree",
      language: "JavaScript",
      runtime: "56 ms",
      memory: "44.5 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(10),
      solved_at: daysAgo(50),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Majority Element",
      platform: "leetcode",
      problem_key: "leetcode-majority-element",
      problem_url: "https://leetcode.com/problems/majority-element/",
      difficulty: "easy",
      tags: ["Array", "Hash Table"],
      pattern: "other",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Boyer-Moore Voting Algorithm. O(n) time O(1) space.",
      mistakes: "First tried HashMap which works but not optimal.",
      similar_problems: "Majority Element II",
      language: "JavaScript",
      runtime: "52 ms",
      memory: "46.2 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-7),
      solved_at: daysAgo(30),
      source: "extension",
    },

    // ── LEETCODE MEDIUM (19) ────────────────────────────────

    {
      user_id: DEMO_USER_ID,
      problem_name: "Longest Substring Without Repeating Characters",
      platform: "leetcode",
      problem_key: "leetcode-longest-substring-without-repeating-characters",
      problem_url:
        "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
      difficulty: "medium",
      tags: ["Hash Table", "String", "Sliding Window"],
      pattern: "sliding_window",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach: "Sliding window with HashMap storing last index of each char.",
      mistakes: null,
      similar_problems: "Minimum Window Substring",
      language: "JavaScript",
      runtime: "76 ms",
      memory: "46.8 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(12),
      solved_at: daysAgo(60),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "3Sum",
      platform: "leetcode",
      problem_key: "leetcode-3sum",
      problem_url: "https://leetcode.com/problems/3sum/",
      difficulty: "medium",
      tags: ["Array", "Two Pointers", "Sorting"],
      pattern: "two_pointers",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "30-60",
      user_difficulty: "medium",
      approach:
        "Sort + fix one element + two pointer scan. Skip duplicates carefully.",
      mistakes: "Duplicate handling tripped me up.",
      similar_problems: "Two Sum, 4Sum",
      language: "JavaScript",
      runtime: "116 ms",
      memory: "52.4 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-4),
      solved_at: daysAgo(45),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Container With Most Water",
      platform: "leetcode",
      problem_key: "leetcode-container-with-most-water",
      problem_url: "https://leetcode.com/problems/container-with-most-water/",
      difficulty: "medium",
      tags: ["Array", "Two Pointers", "Greedy"],
      pattern: "two_pointers",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "medium",
      approach:
        "Two pointers from both ends. Move pointer with smaller height inward.",
      mistakes: null,
      similar_problems: "Trapping Rain Water",
      language: "JavaScript",
      runtime: "64 ms",
      memory: "50.8 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.7,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(16),
      solved_at: daysAgo(65),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Coin Change",
      platform: "leetcode",
      problem_key: "leetcode-coin-change",
      problem_url: "https://leetcode.com/problems/coin-change/",
      difficulty: "medium",
      tags: ["Array", "Dynamic Programming"],
      pattern: "dp",
      status: "solved",
      confidence: "low",
      solve_help: "saw_solution",
      time_taken: ">60",
      user_difficulty: "hard",
      approach: "Bottom-up DP. dp[amount] = min coins needed.",
      mistakes: "Confused top-down vs bottom-up. Took too long.",
      similar_problems: "Coin Change II, Perfect Squares",
      language: "JavaScript",
      runtime: "108 ms",
      memory: "48.2 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.18,
      sm2_repetitions: 0,
      sm2_next_review: nextReview(-10),
      solved_at: daysAgo(20),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Word Search",
      platform: "leetcode",
      problem_key: "leetcode-word-search",
      problem_url: "https://leetcode.com/problems/word-search/",
      difficulty: "medium",
      tags: ["Array", "Backtracking", "Matrix"],
      pattern: "backtracking",
      status: "solved",
      confidence: "medium",
      solve_help: "hints",
      time_taken: "30-60",
      user_difficulty: "medium",
      approach:
        "DFS backtracking. Mark cell visited with '#', restore after each path.",
      mistakes: "Initially forgot to restore visited cells.",
      similar_problems: "Word Search II",
      language: "JavaScript",
      runtime: "296 ms",
      memory: "47.1 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-2),
      solved_at: daysAgo(28),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Number of Islands",
      platform: "leetcode",
      problem_key: "leetcode-number-of-islands",
      problem_url: "https://leetcode.com/problems/number-of-islands/",
      difficulty: "medium",
      tags: ["Array", "DFS", "BFS", "Matrix"],
      pattern: "bfs",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach: "DFS flood fill. For each '1' run DFS marking connected cells.",
      mistakes: null,
      similar_problems: "Max Area of Island",
      language: "JavaScript",
      runtime: "88 ms",
      memory: "52.6 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(7),
      solved_at: daysAgo(52),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Maximum Subarray",
      platform: "leetcode",
      problem_key: "leetcode-maximum-subarray",
      problem_url: "https://leetcode.com/problems/maximum-subarray/",
      difficulty: "medium",
      tags: ["Array", "Dynamic Programming"],
      pattern: "dp",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Kadane's algorithm. Keep running sum, reset to 0 if negative.",
      mistakes: null,
      similar_problems: "Maximum Product Subarray",
      language: "JavaScript",
      runtime: "72 ms",
      memory: "50.4 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.8,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(19),
      solved_at: daysAgo(72),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Merge Intervals",
      platform: "leetcode",
      problem_key: "leetcode-merge-intervals",
      problem_url: "https://leetcode.com/problems/merge-intervals/",
      difficulty: "medium",
      tags: ["Array", "Sorting"],
      pattern: "merge_intervals",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach: "Sort by start time. Merge if current.start <= last.end.",
      mistakes: "Off-by-one on merge condition.",
      similar_problems: "Insert Interval",
      language: "JavaScript",
      runtime: "84 ms",
      memory: "47.8 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-6),
      solved_at: daysAgo(38),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Jump Game",
      platform: "leetcode",
      problem_key: "leetcode-jump-game",
      problem_url: "https://leetcode.com/problems/jump-game/",
      difficulty: "medium",
      tags: ["Array", "Greedy"],
      pattern: "greedy",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach: "Greedy. Track maxReach. If i > maxReach return false.",
      mistakes: null,
      similar_problems: "Jump Game II",
      language: "JavaScript",
      runtime: "64 ms",
      memory: "49.8 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(11),
      solved_at: daysAgo(55),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "House Robber",
      platform: "leetcode",
      problem_key: "leetcode-house-robber",
      problem_url: "https://leetcode.com/problems/house-robber/",
      difficulty: "medium",
      tags: ["Array", "Dynamic Programming"],
      pattern: "dp",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "dp[i] = max(dp[i-1], dp[i-2] + nums[i]). Space optimized.",
      mistakes: null,
      similar_problems: "House Robber II",
      language: "JavaScript",
      runtime: "48 ms",
      memory: "40.2 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.8,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(17),
      solved_at: daysAgo(62),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Find Minimum in Rotated Sorted Array",
      platform: "leetcode",
      problem_key: "leetcode-find-minimum-in-rotated-sorted-array",
      problem_url:
        "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
      difficulty: "medium",
      tags: ["Array", "Binary Search"],
      pattern: "binary_search",
      status: "solved",
      confidence: "medium",
      solve_help: "hints",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach: "Binary search. If mid > right the min is in right half.",
      mistakes: "Kept confusing which half to search.",
      similar_problems: "Search in Rotated Sorted Array",
      language: "JavaScript",
      runtime: "56 ms",
      memory: "41.6 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-1),
      solved_at: daysAgo(25),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Search a 2D Matrix",
      platform: "leetcode",
      problem_key: "leetcode-search-a-2d-matrix",
      problem_url: "https://leetcode.com/problems/search-a-2d-matrix/",
      difficulty: "medium",
      tags: ["Array", "Binary Search", "Matrix"],
      pattern: "binary_search",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "medium",
      approach: "Treat 2D as 1D. mid = matrix[mid/cols][mid%cols].",
      mistakes: null,
      similar_problems: "Search a 2D Matrix II",
      language: "JavaScript",
      runtime: "60 ms",
      memory: "42.8 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.7,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(9),
      solved_at: daysAgo(48),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Course Schedule",
      platform: "leetcode",
      problem_key: "leetcode-course-schedule",
      problem_url: "https://leetcode.com/problems/course-schedule/",
      difficulty: "medium",
      tags: ["DFS", "BFS", "Graph", "Topological Sort"],
      pattern: "bfs",
      status: "solved",
      confidence: "medium",
      solve_help: "hints",
      time_taken: "30-60",
      user_difficulty: "medium",
      approach: "Topological sort via BFS. Build indegree array.",
      mistakes: "Confused directed vs undirected cycle detection.",
      similar_problems: "Course Schedule II",
      language: "JavaScript",
      runtime: "92 ms",
      memory: "47.2 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-8),
      solved_at: daysAgo(32),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Longest Palindromic Substring",
      platform: "leetcode",
      problem_key: "leetcode-longest-palindromic-substring",
      problem_url:
        "https://leetcode.com/problems/longest-palindromic-substring/",
      difficulty: "medium",
      tags: ["String", "Dynamic Programming"],
      pattern: "dp",
      status: "solved",
      confidence: "low",
      solve_help: "hints",
      time_taken: "30-60",
      user_difficulty: "medium",
      approach:
        "Expand around center for both odd and even length palindromes.",
      mistakes:
        "DP table approach is O(n²) space — expand-around-center is better.",
      similar_problems: "Palindromic Substrings",
      language: "JavaScript",
      runtime: "84 ms",
      memory: "46.4 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.3,
      sm2_repetitions: 1,
      sm2_next_review: nextReview(-12),
      solved_at: daysAgo(15),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Subsets",
      platform: "leetcode",
      problem_key: "leetcode-subsets",
      problem_url: "https://leetcode.com/problems/subsets/",
      difficulty: "medium",
      tags: ["Array", "Backtracking"],
      pattern: "backtracking",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach: "Backtracking. At each index choose to include or exclude.",
      mistakes: "Initially pushed reference instead of copy.",
      similar_problems: "Permutations, Combination Sum",
      language: "JavaScript",
      runtime: "60 ms",
      memory: "44.5 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(2),
      solved_at: daysAgo(22),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Combination Sum",
      platform: "leetcode",
      problem_key: "leetcode-combination-sum",
      problem_url: "https://leetcode.com/problems/combination-sum/",
      difficulty: "medium",
      tags: ["Array", "Backtracking"],
      pattern: "backtracking",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach:
        "Backtracking with start index. Reuse same element by not incrementing.",
      mistakes: "Forgot to pass remaining = target - candidate recursively.",
      similar_problems: "Combination Sum II",
      language: "JavaScript",
      runtime: "72 ms",
      memory: "44.8 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(1),
      solved_at: daysAgo(20),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Rotate Array",
      platform: "leetcode",
      problem_key: "leetcode-rotate-array",
      problem_url: "https://leetcode.com/problems/rotate-array/",
      difficulty: "medium",
      tags: ["Array", "Math", "Two Pointers"],
      pattern: "two_pointers",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach:
        "Reverse entire array, then reverse first k, then reverse rest.",
      mistakes: "k = k % n edge case when k > n.",
      similar_problems: "Rotate Image",
      language: "JavaScript",
      runtime: "68 ms",
      memory: "48.2 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(3),
      solved_at: daysAgo(33),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Letter Combinations of a Phone Number",
      platform: "leetcode",
      problem_key: "leetcode-letter-combinations-phone-number",
      problem_url:
        "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
      difficulty: "medium",
      tags: ["Hash Table", "String", "Backtracking"],
      pattern: "backtracking",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach:
        "Backtracking with phone mapping. Build combinations char by char.",
      mistakes: null,
      similar_problems: "Generate Parentheses",
      language: "JavaScript",
      runtime: "56 ms",
      memory: "42.0 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(6),
      solved_at: daysAgo(42),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Spiral Matrix",
      platform: "leetcode",
      problem_key: "leetcode-spiral-matrix",
      problem_url: "https://leetcode.com/problems/spiral-matrix/",
      difficulty: "medium",
      tags: ["Array", "Matrix", "Simulation"],
      pattern: "other",
      status: "solved",
      confidence: "low",
      solve_help: "saw_solution",
      time_taken: ">60",
      user_difficulty: "hard",
      approach:
        "Layer-by-layer peeling. Track top, bottom, left, right boundaries.",
      mistakes:
        "Boundary conditions very tricky with single row/col edge cases.",
      similar_problems: "Spiral Matrix II",
      language: "JavaScript",
      runtime: "52 ms",
      memory: "40.9 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.18,
      sm2_repetitions: 0,
      sm2_next_review: nextReview(-14),
      solved_at: daysAgo(18),
      source: "extension",
    },

    // ── LEETCODE HARD (6) ───────────────────────────────────

    {
      user_id: DEMO_USER_ID,
      problem_name: "Trapping Rain Water",
      platform: "leetcode",
      problem_key: "leetcode-trapping-rain-water",
      problem_url: "https://leetcode.com/problems/trapping-rain-water/",
      difficulty: "hard",
      tags: ["Array", "Two Pointers", "Stack"],
      pattern: "two_pointers",
      status: "solved",
      confidence: "medium",
      solve_help: "hints",
      time_taken: "30-60",
      user_difficulty: "hard",
      approach:
        "Two pointer. Track maxLeft and maxRight. Water = min(maxL, maxR) - height[i].",
      mistakes: "First attempt was O(n²) brute force.",
      similar_problems: "Container With Most Water",
      language: "JavaScript",
      runtime: "60 ms",
      memory: "45.2 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-9),
      solved_at: daysAgo(26),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Median of Two Sorted Arrays",
      platform: "leetcode",
      problem_key: "leetcode-median-of-two-sorted-arrays",
      problem_url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
      difficulty: "hard",
      tags: ["Array", "Binary Search"],
      pattern: "binary_search",
      status: "solved",
      confidence: "low",
      solve_help: "saw_solution",
      time_taken: ">60",
      user_difficulty: "hard",
      approach: "Binary search on smaller array to find partition.",
      mistakes: "Edge cases for partition at 0 or n are very subtle.",
      similar_problems: "Find K-th Smallest in Sorted Matrix",
      language: "JavaScript",
      runtime: "88 ms",
      memory: "47.8 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.1,
      sm2_repetitions: 0,
      sm2_next_review: nextReview(-15),
      solved_at: daysAgo(16),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "N-Queens",
      platform: "leetcode",
      problem_key: "leetcode-n-queens",
      problem_url: "https://leetcode.com/problems/n-queens/",
      difficulty: "hard",
      tags: ["Array", "Backtracking"],
      pattern: "backtracking",
      status: "solved",
      confidence: "medium",
      solve_help: "hints",
      time_taken: "30-60",
      user_difficulty: "hard",
      approach: "Backtracking with sets for cols, diagonals, anti-diagonals.",
      mistakes: "Diagonal constraint: row-col and row+col took a while.",
      similar_problems: "N-Queens II, Sudoku Solver",
      language: "JavaScript",
      runtime: "64 ms",
      memory: "43.6 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(4),
      solved_at: daysAgo(36),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Word Ladder",
      platform: "leetcode",
      problem_key: "leetcode-word-ladder",
      problem_url: "https://leetcode.com/problems/word-ladder/",
      difficulty: "hard",
      tags: ["Hash Table", "String", "BFS"],
      pattern: "bfs",
      status: "solved",
      confidence: "low",
      solve_help: "saw_solution",
      time_taken: ">60",
      user_difficulty: "hard",
      approach: "BFS with wildcard intermediate states.",
      mistakes: "Naive BFS is O(n²m). Pattern key approach is essential.",
      similar_problems: "Word Ladder II",
      language: "JavaScript",
      runtime: "148 ms",
      memory: "52.8 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.1,
      sm2_repetitions: 0,
      sm2_next_review: nextReview(-11),
      solved_at: daysAgo(14),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Largest Rectangle in Histogram",
      platform: "leetcode",
      problem_key: "leetcode-largest-rectangle-histogram",
      problem_url:
        "https://leetcode.com/problems/largest-rectangle-in-histogram/",
      difficulty: "hard",
      tags: ["Array", "Stack", "Monotonic Stack"],
      pattern: "other",
      status: "solved",
      confidence: "low",
      solve_help: "saw_solution",
      time_taken: ">60",
      user_difficulty: "hard",
      approach: "Monotonic stack. Pop when current bar shorter, compute area.",
      mistakes:
        "Width calc after pop: width = i - stack[-1] - 1 was confusing.",
      similar_problems: "Maximal Rectangle",
      language: "JavaScript",
      runtime: "96 ms",
      memory: "50.2 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.1,
      sm2_repetitions: 0,
      sm2_next_review: nextReview(-13),
      solved_at: daysAgo(12),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Serialize and Deserialize Binary Tree",
      platform: "leetcode",
      problem_key: "leetcode-serialize-deserialize-binary-tree",
      problem_url:
        "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
      difficulty: "hard",
      tags: ["String", "Tree", "BFS"],
      pattern: "bfs",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "30-60",
      user_difficulty: "hard",
      approach: "BFS level order. '#' for null. Split by comma on deserialize.",
      mistakes: "Queue-based deserialize — careful about when to dequeue.",
      similar_problems: "Serialize and Deserialize BST",
      language: "JavaScript",
      runtime: "120 ms",
      memory: "53.4 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(5),
      solved_at: daysAgo(44),
      source: "extension",
    },

    // ── CODEFORCES EASY (8) ─────────────────────────────────

    {
      user_id: DEMO_USER_ID,
      problem_name: "Watermelon",
      platform: "codeforces",
      problem_key: "codeforces-4-a",
      problem_url: "https://codeforces.com/problemset/problem/4/A",
      difficulty: "easy",
      cf_rating: 800,
      tags: ["brute force", "math"],
      pattern: "math",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "If w > 2 and w is even, YES. Otherwise NO.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "46 ms",
      memory: "8.3 MB",
      sm2_interval: 30,
      sm2_ease_factor: 2.9,
      sm2_repetitions: 5,
      sm2_next_review: nextReview(25),
      solved_at: daysAgo(86),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Next Round",
      platform: "codeforces",
      problem_key: "codeforces-158-a",
      problem_url: "https://codeforces.com/problemset/problem/158/A",
      difficulty: "easy",
      cf_rating: 800,
      tags: ["implementation"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Count how many scores >= score[k-1] AND score > 0.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "48 ms",
      memory: "8.7 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.7,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(15),
      solved_at: daysAgo(74),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Bit++",
      platform: "codeforces",
      problem_key: "codeforces-282-a",
      problem_url: "https://codeforces.com/problemset/problem/282/A",
      difficulty: "easy",
      cf_rating: 800,
      tags: ["implementation"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Check second char. '+' means increment, '-' means decrement.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "46 ms",
      memory: "8.2 MB",
      sm2_interval: 30,
      sm2_ease_factor: 2.9,
      sm2_repetitions: 5,
      sm2_next_review: nextReview(27),
      solved_at: daysAgo(84),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Boy or Girl",
      platform: "codeforces",
      problem_key: "codeforces-236-a",
      problem_url: "https://codeforces.com/problemset/problem/236/A",
      difficulty: "easy",
      cf_rating: 900,
      tags: ["implementation", "strings"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Count distinct chars. If odd Boy, If even Girl.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "52 ms",
      memory: "8.8 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.7,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(18),
      solved_at: daysAgo(76),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Team",
      platform: "codeforces",
      problem_key: "codeforces-231-a",
      problem_url: "https://codeforces.com/problemset/problem/231/A",
      difficulty: "easy",
      cf_rating: 800,
      tags: ["greedy", "implementation"],
      pattern: "greedy",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach:
        "For each problem count how many of three can solve. If >= 2 increment.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "50 ms",
      memory: "8.5 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.8,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(16),
      solved_at: daysAgo(66),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Young Physicist",
      platform: "codeforces",
      problem_key: "codeforces-42-a",
      problem_url: "https://codeforces.com/problemset/problem/42/A",
      difficulty: "easy",
      cf_rating: 1000,
      tags: ["implementation", "math"],
      pattern: "math",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Sum all x, y, z components. If all zero output YES.",
      mistakes: "Parsing the vector input format took a moment.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "54 ms",
      memory: "8.9 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.5,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(8),
      solved_at: daysAgo(58),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Helpful Maths",
      platform: "codeforces",
      problem_key: "codeforces-339-a",
      problem_url: "https://codeforces.com/problemset/problem/339/A",
      difficulty: "easy",
      cf_rating: 1200,
      tags: ["greedy", "sortings", "strings"],
      pattern: "greedy",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Extract all digits, sort them, join with + signs.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "52 ms",
      memory: "9.0 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.7,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(13),
      solved_at: daysAgo(58),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Stones on the Table",
      platform: "codeforces",
      problem_key: "codeforces-266-a",
      problem_url: "https://codeforces.com/problemset/problem/266/A",
      difficulty: "easy",
      cf_rating: 1200,
      tags: ["implementation", "greedy"],
      pattern: "greedy",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Count adjacent duplicates — each can be removed.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "54 ms",
      memory: "9.0 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(9),
      solved_at: daysAgo(50),
      source: "extension",
    },

    // ── CODEFORCES MEDIUM (13) ──────────────────────────────

    {
      user_id: DEMO_USER_ID,
      problem_name: "Pangram",
      platform: "codeforces",
      problem_key: "codeforces-520-a",
      problem_url: "https://codeforces.com/problemset/problem/520/A",
      difficulty: "medium",
      cf_rating: 1100,
      tags: ["strings", "implementation"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Lowercase and use Set. Check if size == 26.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "62 ms",
      memory: "9.2 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(11),
      solved_at: daysAgo(56),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Beautiful Matrix",
      platform: "codeforces",
      problem_key: "codeforces-364-b",
      problem_url: "https://codeforces.com/problemset/problem/364/B",
      difficulty: "medium",
      cf_rating: 1400,
      tags: ["implementation", "math"],
      pattern: "math",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach:
        "Find position of 0. Calculate moves to center: |row-2| + |col-2|.",
      mistakes: "1-indexed vs 0-indexed tripped me up.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "64 ms",
      memory: "9.4 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-3),
      solved_at: daysAgo(28),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Dubstep",
      platform: "codeforces",
      problem_key: "codeforces-208-b",
      problem_url: "https://codeforces.com/problemset/problem/208/B",
      difficulty: "medium",
      cf_rating: 1400,
      tags: ["implementation", "strings"],
      pattern: "other",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach: "Remove all WUB, split by spaces, filter empty strings.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "66 ms",
      memory: "9.3 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(1),
      solved_at: daysAgo(20),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Vanya and Fence",
      platform: "codeforces",
      problem_key: "codeforces-677-a",
      problem_url: "https://codeforces.com/problemset/problem/677/A",
      difficulty: "medium",
      cf_rating: 1300,
      tags: ["implementation"],
      pattern: "other",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach:
        "Simulate. Track remaining width. Height > fence takes 2 width.",
      mistakes: "Off by one on width tracking.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "68 ms",
      memory: "9.4 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(4),
      solved_at: daysAgo(32),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Soldier and Bananas",
      platform: "codeforces",
      problem_key: "codeforces-546-a",
      problem_url: "https://codeforces.com/problemset/problem/546/A",
      difficulty: "medium",
      cf_rating: 1300,
      tags: ["implementation", "math"],
      pattern: "math",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Total cost = k*(k+1)/2 * w. Answer = max(0, total - n).",
      mistakes: "Forgot to handle case where soldier has enough money.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "60 ms",
      memory: "9.2 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.5,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-2),
      solved_at: daysAgo(24),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Petya and Strings",
      platform: "codeforces",
      problem_key: "codeforces-848-b",
      problem_url: "https://codeforces.com/problemset/problem/848/B",
      difficulty: "medium",
      cf_rating: 1400,
      tags: ["implementation", "strings"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach:
        "Compare chars. If diff > 1 decide immediately. If diff = 1, lowercase.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "62 ms",
      memory: "9.2 MB",
      sm2_interval: 15,
      sm2_ease_factor: 2.6,
      sm2_repetitions: 3,
      sm2_next_review: nextReview(10),
      solved_at: daysAgo(48),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Primes or Palindromes",
      platform: "codeforces",
      problem_key: "codeforces-568-b",
      problem_url: "https://codeforces.com/problemset/problem/568/B",
      difficulty: "medium",
      cf_rating: 1500,
      tags: ["brute force", "math", "number theory"],
      pattern: "math",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach: "Sieve of Eratosthenes up to 2*n. Count primes vs palindromes.",
      mistakes: "Off-by-one in sieve upper bound.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "84 ms",
      memory: "10.2 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.4,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(-1),
      solved_at: daysAgo(22),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Anton and Danik",
      platform: "codeforces",
      problem_key: "codeforces-604-a",
      problem_url: "https://codeforces.com/problemset/problem/604/A",
      difficulty: "medium",
      cf_rating: 1200,
      tags: ["implementation"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Count A wins and D wins. Compare at end.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "58 ms",
      memory: "9.1 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.7,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(14),
      solved_at: daysAgo(60),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Polo the Penguin and Strings",
      platform: "codeforces",
      problem_key: "codeforces-288-b",
      problem_url: "https://codeforces.com/problemset/problem/288/B",
      difficulty: "medium",
      cf_rating: 1500,
      tags: ["implementation", "strings"],
      pattern: "two_pointers",
      status: "solved",
      confidence: "low",
      solve_help: "hints",
      time_taken: "30-60",
      user_difficulty: "medium",
      approach:
        "Find runs of Zs. Between Z-runs, check if A and B counts balance.",
      mistakes: "The interleaving condition was non-trivial.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "78 ms",
      memory: "9.8 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.3,
      sm2_repetitions: 1,
      sm2_next_review: nextReview(-6),
      solved_at: daysAgo(18),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "George and Accommodation",
      platform: "codeforces",
      problem_key: "codeforces-467-a",
      problem_url: "https://codeforces.com/problemset/problem/467/A",
      difficulty: "medium",
      cf_rating: 1200,
      tags: ["implementation"],
      pattern: "other",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach:
        "Count rooms where both inhabitants non-zero and capacity >= 2.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "56 ms",
      memory: "9.1 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.8,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(17),
      solved_at: daysAgo(64),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Bulbs",
      platform: "codeforces",
      problem_key: "codeforces-342-a",
      problem_url: "https://codeforces.com/problemset/problem/342/A",
      difficulty: "medium",
      cf_rating: 1300,
      tags: ["implementation"],
      pattern: "other",
      status: "solved",
      confidence: "medium",
      solve_help: "no_help",
      time_taken: "15-30",
      user_difficulty: "medium",
      approach:
        "Track toggle parity. Bulb lights if starts OFF + parity ODD, or ON + parity EVEN.",
      mistakes: "Parity logic needed careful thought.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "70 ms",
      memory: "9.3 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(2),
      solved_at: daysAgo(22),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Bear and Prime 100",
      platform: "codeforces",
      problem_key: "codeforces-660-a",
      problem_url: "https://codeforces.com/problemset/problem/660/A",
      difficulty: "medium",
      cf_rating: 900,
      tags: ["math", "number theory"],
      pattern: "math",
      status: "solved",
      confidence: "high",
      solve_help: "no_help",
      time_taken: "<15",
      user_difficulty: "easy",
      approach: "Ask all primes up to 100 and check divisibility.",
      mistakes: null,
      similar_problems: null,
      language: "JavaScript",
      runtime: "62 ms",
      memory: "9.1 MB",
      sm2_interval: 21,
      sm2_ease_factor: 2.8,
      sm2_repetitions: 4,
      sm2_next_review: nextReview(20),
      solved_at: daysAgo(78),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Greg and Array",
      platform: "codeforces",
      problem_key: "codeforces-295-b",
      problem_url: "https://codeforces.com/problemset/problem/295/B",
      difficulty: "medium",
      cf_rating: 1900,
      tags: ["data structures", "implementation"],
      pattern: "other",
      status: "solved",
      confidence: "medium",
      solve_help: "hints",
      time_taken: "30-60",
      user_difficulty: "hard",
      approach:
        "Difference array for range updates. Count operations affecting each index.",
      mistakes: "Constructing difference array took careful indexing.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "136 ms",
      memory: "12.6 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(5),
      solved_at: daysAgo(40),
      source: "extension",
    },

    // ── CODEFORCES HARD (4) ─────────────────────────────────

    {
      user_id: DEMO_USER_ID,
      problem_name: "Vasya and String",
      platform: "codeforces",
      problem_key: "codeforces-686-c",
      problem_url: "https://codeforces.com/problemset/problem/686/C",
      difficulty: "hard",
      cf_rating: 1900,
      tags: ["binary search", "greedy", "strings"],
      pattern: "binary_search",
      status: "solved",
      confidence: "low",
      solve_help: "saw_solution",
      time_taken: ">60",
      user_difficulty: "hard",
      approach:
        "Binary search on answer length. Check valid segment with sliding window.",
      mistakes: "Check function took multiple attempts to get right.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "124 ms",
      memory: "11.8 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.1,
      sm2_repetitions: 0,
      sm2_next_review: nextReview(-16),
      solved_at: daysAgo(17),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Mahmoud and Ehab and the MEX",
      platform: "codeforces",
      problem_key: "codeforces-862-b",
      problem_url: "https://codeforces.com/problemset/problem/862/B",
      difficulty: "hard",
      cf_rating: 1900,
      tags: ["constructive algorithms", "greedy"],
      pattern: "greedy",
      status: "solved",
      confidence: "low",
      solve_help: "saw_solution",
      time_taken: ">60",
      user_difficulty: "hard",
      approach:
        "Use multiset. For each missing number, replace the largest element.",
      mistakes: "Greedy choice of which element to replace was not obvious.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "112 ms",
      memory: "11.4 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.1,
      sm2_repetitions: 0,
      sm2_next_review: nextReview(-18),
      solved_at: daysAgo(19),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Ants",
      platform: "codeforces",
      problem_key: "codeforces-704-b",
      problem_url: "https://codeforces.com/problemset/problem/704/B",
      difficulty: "hard",
      cf_rating: 2000,
      tags: ["dp", "greedy"],
      pattern: "dp",
      status: "solved",
      confidence: "low",
      solve_help: "saw_solution",
      time_taken: ">60",
      user_difficulty: "hard",
      approach:
        "DP with bitmask. dp[mask] = min cost to place ants in positions.",
      mistakes: "Bitmask DP was completely new — studied the pattern first.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "148 ms",
      memory: "13.2 MB",
      sm2_interval: 1,
      sm2_ease_factor: 2.0,
      sm2_repetitions: 0,
      sm2_next_review: nextReview(-20),
      solved_at: daysAgo(21),
      source: "extension",
    },
    {
      user_id: DEMO_USER_ID,
      problem_name: "Polo the Penguin and Powers",
      platform: "codeforces",
      problem_key: "codeforces-289-b",
      problem_url: "https://codeforces.com/problemset/problem/289/B",
      difficulty: "hard",
      cf_rating: 1900,
      tags: ["constructive algorithms", "math"],
      pattern: "math",
      status: "solved",
      confidence: "medium",
      solve_help: "hints",
      time_taken: "30-60",
      user_difficulty: "hard",
      approach:
        "Construct sequences using powers of 2. Each number appears in exactly one sequence.",
      mistakes: "The construction approach took a while to visualise.",
      similar_problems: null,
      language: "JavaScript",
      runtime: "108 ms",
      memory: "11.2 MB",
      sm2_interval: 6,
      sm2_ease_factor: 2.36,
      sm2_repetitions: 2,
      sm2_next_review: nextReview(3),
      solved_at: daysAgo(38),
      source: "extension",
    },
  ];
}

// ── Main handler ──────────────────────────────────────────────

export async function GET(request: NextRequest) {
  return NextResponse.json(
    { message: "Use POST to trigger seed" },
    { status: 405 },
  );
}

export async function POST(request: NextRequest) {
  try {
    // ── Auth check — verify secret key ─────────────────────
    const authHeader = request.headers.get("Authorization");
    const secret = authHeader?.replace("Bearer ", "").trim();
    const expectedSecret = process.env.SEED_SECRET;

    if (!expectedSecret) {
      return NextResponse.json(
        { error: "SEED_SECRET not configured" },
        { status: 500 },
      );
    }

    if (secret !== expectedSecret) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // ── Connect with service role key (bypasses RLS) ────────
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
    );

    const startTime = Date.now();

    // ── 1. Clear existing demo data ─────────────────────────
    const tables = [
      "submission_history",
      "cf_group_problems",
      "cf_groups",
      "problems",
    ];

    for (const table of tables) {
      const { error } = await supabase
        .from(table)
        .delete()
        .eq("user_id", DEMO_USER_ID);

      if (error) {
        return NextResponse.json(
          { error: `Failed to clear ${table}: ${error.message}` },
          { status: 500 },
        );
      }
    }

    // ── 2. Insert problems in batches ───────────────────────
    const problems = getProblems();

    for (let i = 0; i < problems.length; i += 20) {
      const batch = problems.slice(i, i + 20);
      const { error } = await supabase.from("problems").insert(batch as any);

      if (error) {
        return NextResponse.json(
          { error: `Failed to insert problems batch: ${error.message}` },
          { status: 500 },
        );
      }
    }

    // ── 3. Insert CF groups ─────────────────────────────────
    const cfGroups = [
      {
        user_id: DEMO_USER_ID,
        group_code: "DEMO001XYZ",
        group_name: "DSA Bootcamp — Batch 12",
        group_url: "https://codeforces.com/group/DEMO001XYZ/contests",
        total_problems: 24,
        solved_count: 14,
        attempted_count: 4,
        todo_count: 6,
        progress_pct: 58,
        last_synced: daysAgo(1),
        sync_status: "success",
      },
      {
        user_id: DEMO_USER_ID,
        group_code: "DEMO002ABC",
        group_name: "Competitive Programming Club",
        group_url: "https://codeforces.com/group/DEMO002ABC/contests",
        total_problems: 18,
        solved_count: 11,
        attempted_count: 2,
        todo_count: 5,
        progress_pct: 61,
        last_synced: daysAgo(2),
        sync_status: "success",
      },
    ];

    const { data: groupRows, error: groupError } = await supabase
      .from("cf_groups")
      .insert(cfGroups as any)
      .select("id, group_code");

    if (groupError) {
      return NextResponse.json(
        { error: `Failed to insert CF groups: ${groupError.message}` },
        { status: 500 },
      );
    }

    // ── 4. Insert CF group problems ─────────────────────────
    const group1Id = groupRows?.find(
      (g: any) => g.group_code === "DEMO001XYZ",
    )?.id;
    const group2Id = groupRows?.find(
      (g: any) => g.group_code === "DEMO002ABC",
    )?.id;

    if (group1Id && group2Id) {
      const cfGroupProblems = [
        ...["A", "B", "C", "D", "E", "F"].map((idx, i) => ({
          group_id: group1Id,
          user_id: DEMO_USER_ID,
          contest_id: "100001",
          contest_name: "Week 1 — Arrays & Strings",
          problem_index: idx,
          problem_name: [
            "Two Strings",
            "Reverse Run",
            "Max Segment",
            "Count Pairs",
            "Sort Check",
            "Grid Walk",
          ][i],
          problem_url: `https://codeforces.com/group/DEMO001XYZ/contest/100001/problem/${idx}`,
          cf_rating: [900, 1100, 1300, 1500, 1700, 1900][i],
          cf_status: [
            "solved",
            "solved",
            "solved",
            "solved",
            "attempted",
            "todo",
          ][i],
          solved_at:
            ["solved", "solved", "solved", "solved", "attempted", "todo"][i] ===
            "solved"
              ? daysAgo(20 + i * 3)
              : null,
        })),
        ...["A", "B", "C", "D", "E", "F"].map((idx, i) => ({
          group_id: group1Id,
          user_id: DEMO_USER_ID,
          contest_id: "100002",
          contest_name: "Week 2 — Dynamic Programming",
          problem_index: idx,
          problem_name: [
            "Stair Climb",
            "Frog Jump",
            "Matrix Path",
            "Knapsack Easy",
            "String DP",
            "Tree DP",
          ][i],
          problem_url: `https://codeforces.com/group/DEMO001XYZ/contest/100002/problem/${idx}`,
          cf_rating: [1000, 1200, 1400, 1600, 1800, 2000][i],
          cf_status: [
            "solved",
            "solved",
            "solved",
            "solved",
            "attempted",
            "todo",
          ][i],
          solved_at:
            ["solved", "solved", "solved", "solved", "attempted", "todo"][i] ===
            "solved"
              ? daysAgo(10 + i * 2)
              : null,
        })),
        ...["A", "B", "C"].map((idx, i) => ({
          group_id: group2Id,
          user_id: DEMO_USER_ID,
          contest_id: "200001",
          contest_name: "Round 1 — Graphs",
          problem_index: idx,
          problem_name: ["BFS Start", "DFS Islands", "Shortest Path"][i],
          problem_url: `https://codeforces.com/group/DEMO002ABC/contest/200001/problem/${idx}`,
          cf_rating: [1100, 1400, 1700][i],
          cf_status: ["solved", "solved", "attempted"][i],
          solved_at:
            ["solved", "solved", "attempted"][i] === "solved"
              ? daysAgo(15 + i * 4)
              : null,
        })),
        ...["A", "B", "C"].map((idx, i) => ({
          group_id: group2Id,
          user_id: DEMO_USER_ID,
          contest_id: "200002",
          contest_name: "Round 2 — Trees",
          problem_index: idx,
          problem_name: ["Tree Height", "LCA Query", "Subtree Sum"][i],
          problem_url: `https://codeforces.com/group/DEMO002ABC/contest/200002/problem/${idx}`,
          cf_rating: [1200, 1500, 1800][i],
          cf_status: ["solved", "solved", "todo"][i],
          solved_at:
            ["solved", "solved", "todo"][i] === "solved"
              ? daysAgo(8 + i * 3)
              : null,
        })),
      ];

      const { error: cfpError } = await supabase
        .from("cf_group_problems")
        .insert(cfGroupProblems as any);

      if (cfpError) {
        return NextResponse.json(
          { error: `Failed to insert CF group problems: ${cfpError.message}` },
          { status: 500 },
        );
      }
    }

    // ── 5. Insert submission history ────────────────────────
    const history = [
      {
        user_id: DEMO_USER_ID,
        problem_key: "leetcode-coin-change",
        platform: "leetcode",
        submission_id: "demo-s001",
        status: "attempted",
        language: "JavaScript",
        runtime: null,
        memory: null,
        confidence: null,
        submitted_at: daysAgo(25),
      },
      {
        user_id: DEMO_USER_ID,
        problem_key: "leetcode-coin-change",
        platform: "leetcode",
        submission_id: "demo-s002",
        status: "solved",
        language: "JavaScript",
        runtime: "108 ms",
        memory: "48.2 MB",
        confidence: "low",
        submitted_at: daysAgo(20),
      },
      {
        user_id: DEMO_USER_ID,
        problem_key: "leetcode-3sum",
        platform: "leetcode",
        submission_id: "demo-s003",
        status: "attempted",
        language: "JavaScript",
        runtime: null,
        memory: null,
        confidence: null,
        submitted_at: daysAgo(50),
      },
      {
        user_id: DEMO_USER_ID,
        problem_key: "leetcode-3sum",
        platform: "leetcode",
        submission_id: "demo-s004",
        status: "solved",
        language: "JavaScript",
        runtime: "116 ms",
        memory: "52.4 MB",
        confidence: "medium",
        submitted_at: daysAgo(45),
      },
      {
        user_id: DEMO_USER_ID,
        problem_key: "leetcode-trapping-rain-water",
        platform: "leetcode",
        submission_id: "demo-s005",
        status: "solved",
        language: "JavaScript",
        runtime: "60 ms",
        memory: "45.2 MB",
        confidence: "medium",
        submitted_at: daysAgo(26),
      },
    ];

    const { error: histError } = await supabase
      .from("submission_history")
      .insert(history as any);

    if (histError) {
      return NextResponse.json(
        { error: `Failed to insert history: ${histError.message}` },
        { status: 500 },
      );
    }

    const duration = Date.now() - startTime;

    return NextResponse.json({
      success: true,
      message: "Demo account reset successfully",
      stats: {
        problems: problems.length,
        cf_groups: cfGroups.length,
        cf_group_problems: 18,
        submission_history: history.length,
        duration_ms: duration,
      },
    });
  } catch (error) {
    const err = error as Error;
    return NextResponse.json(
      { error: err.message || "Internal server error" },
      { status: 500 },
    );
  }
}
